[package]
name = "rk_step_parser"
version.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true

[dependencies]
rk_calc = { path = "../rk_calc" }
rk_cad = { path = "../rk_cad" }
regex = "1.11"
