[workspace]

members = [
    "rk_cad",
    "rk_calc", "rk_step_parser",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT/Apache-2.0"
description = "3D CAD library made in rust"

[workspace.dependencies]
thiserror = "2.0"
anyhow = "1.0"
